spring:
  datasource:
    url: jdbc:postgresql://localhost:${PG_PORT}/${PG_TABLE_NAME}
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
  liquibase:
    enabled: true
    drop-first: false
    default-schema: public

